#!/usr/bin/env python3
"""Print held-out test results generated by the canonical training pipeline."""
import json
from train import train_models

def evaluate():
    _, results = train_models()
    print(results["disclaimer"])
    print(json.dumps(results, indent=2))
    return results

if __name__ == "__main__":
    evaluate()
