// Run with: node scripts/seed-data.js
// Populates sample User/Service/Requirement/Metric/SLO/Incident/RecoveryAction
// data for local demo/testing.
// Requires backend/.env to be configured with a valid MONGO_URI and LLM_API_KEY.

require('dotenv').config({ path: require('path').resolve(__dirname, '../backend/.env') });
const mongoose = require('mongoose');

const User = require('../backend/models/User');
const Service = require('../backend/models/Service');
const Requirement = require('../backend/models/Requirement');
const Metric = require('../backend/models/Metric');
const SLO = require('../backend/models/SLO');
const Incident = require('../backend/models/Incident');
const RecoveryAction = require('../backend/models/RecoveryAction');
const { explainRecoveryDecision } = require('../backend/services/llm.service');

const seed = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected for seeding...');

  // 1. User
  const user = await User.findOneAndUpdate(
    { githubId: 'demo-user' },
    { githubId: 'demo-user', username: 'demo-user', email: 'demo@example.com' },
    { upsert: true, new: true }
  );
  console.log('  ✔ User:', user.username);

  // 2. Service
  const service = await Service.findOneAndUpdate(
    { name: 'demo-checkout-service' },
    {
      name: 'demo-checkout-service',
      repoUrl: 'https://github.com/example/demo-checkout-service',
      owner: user._id,
      namespace: 'default',
      deploymentName: 'demo-checkout-service',
      status: 'running',
    },
    { upsert: true, new: true }
  );
  console.log('  ✔ Service:', service.name);

  // 3. Requirement
  const requirement = await Requirement.findOneAndUpdate(
    { text: 'Checkout should feel fast and reliable', service: service._id },
    { text: 'Checkout should feel fast and reliable', service: service._id, createdBy: user._id },
    { upsert: true, new: true }
  );
  console.log('  ✔ Requirement:', requirement.text);

  // 4. Metric
  const metric = await Metric.findOneAndUpdate(
    { name: 'http_request_duration_seconds', service: service._id },
    {
      name: 'http_request_duration_seconds',
      service: service._id,
      source: 'prometheus',
      queryExpression: 'histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))',
    },
    { upsert: true, new: true }
  );
  console.log('  ✔ Metric:', metric.name);

  // 5. SLO (violated — so the dashboard shows something meaningful)
  const slo = await SLO.findOneAndUpdate(
    { requirement: requirement._id, metric: metric._id },
    {
      requirement: requirement._id,
      metric: metric._id,
      threshold: 300,
      comparator: '<',
      unit: 'ms',
      status: 'violated',
      lastCheckedAt: new Date(),
    },
    { upsert: true, new: true }
  );
  console.log('  ✔ SLO: threshold <', slo.threshold, slo.unit, '- status:', slo.status);

  // 6. Incident
  const incident = await Incident.findOneAndUpdate(
    { service: service._id, slo: slo._id, type: 'active_violation' },
    {
      service: service._id,
      slo: slo._id,
      type: 'active_violation',
      severity: 'high',
      rootCause: 'P95 latency spiked to 620ms due to database connection pool exhaustion under peak load',
      confidence: 0.87,
      rawLogsSnapshot: 'ERROR: connection pool exhausted, 12 pending queries timed out',
      status: 'diagnosing',
    },
    { upsert: true, new: true }
  );
  console.log('  ✔ Incident: severity', incident.severity, '- rootCause:', incident.rootCause.substring(0, 50) + '...');

  // 7. RecoveryAction — reason is generated by a REAL LLM call
  console.log('  ⏳ Calling LLM for recovery explanation...');
  let reason;
  try {
    reason = await explainRecoveryDecision({
      rootCause: incident.rootCause,
      actionType: 'restart',
      businessImpact: 'Checkout page latency exceeds SLO; customers may abandon carts',
    });
    console.log('  ✔ LLM returned reason:', reason.substring(0, 80) + '...');
  } catch (llmErr) {
    console.error('  ✘ LLM call failed:', llmErr.message);
    reason = 'LLM unavailable — manual explanation needed';
  }

  const recovery = await RecoveryAction.findOneAndUpdate(
    { incident: incident._id, service: service._id, actionType: 'restart' },
    {
      incident: incident._id,
      service: service._id,
      actionType: 'restart',
      reason,
      requiresApproval: false,
      status: 'success',
      requirementVerified: false,
    },
    { upsert: true, new: true }
  );
  console.log('  ✔ RecoveryAction:', recovery.actionType, '- status:', recovery.status);

  console.log('\nSeed data created successfully (7 entities).');
  await mongoose.disconnect();
};

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});

